### ISSUE TITLE
Userupdate funktioniert nicht

### ISSUE THREAD

**Issue by SergejDK** [kickvinwl/kickvinwl#103]
User update z.B. beim Bild funktioniert nicht.
Bestimmte Sachen dürfen nicht null sein, die ich übergeben muss aber viele Daten nicht habe.

Wenn ich weitere Daten mitliefere bekommt man ein Fehler im Mapping.

**Comment by Haxhaxdax** [comment]
#102 beachten ;)

**Comment by SergejDK** [comment]
Funktioniert seit dem letzten merge von mir und karl
