### ISSUE TITLE
Get Tip für aktuellen Spieltag nicht möglich

### ISSUE THREAD

**Issue by tobire** [kickvinwl/kickvinwl#105]
Der Zugriff auf die Tipps für den aktuellen Spieltag ist nicht möglich, da der gameday nicht optional ist:
`@Path("/{a:get|Get}/{gameday}/{token}")`

Vorschlag zur Güte: Token nach vorne, Gameday nach hinten, Gameday optional

**Comment by Biotrade** [comment]
Dafür muss der aktuelle Spieltag irgendwo gespeichert sein, da wir den dann alternativ bei einem leeren gameday Übergabeparameter einsetzen müssen. Das ist aktuell nicht möglich.
