### ISSUE TITLE
Login-Aufruf per POST

### ISSUE THREAD

**Issue by tobire** [kickvinwl/kickvinwl#113]
Die Datenübermittlung zum Login sollte im Body einer POST-Request geschehen.
Aktuell werden die Daten als GET in der URL übergeben.

Beispieldaten einer Request an `/login`:
```
{
  'user': 'username',
  'pw': '123456',
  'group': 'GG_EVAULT_Default_Standardfunktionen'
}
```

**Comment by tobire** [comment]
Das Problem ist nicht so kritisch, wie zuerst angenommen, da via HTTPS auch die URL verschlüsselt wird (https://stackoverflow.com/a/499594).

**Comment by Mankianer** [comment]
ist erledigt
