### ISSUE TITLE
Tipp abgeben: Feedback (Erfolgsnachricht o.Ä.)

### ISSUE THREAD

**Issue by g-back** [kickvinwl/kickvinwl#162]
Wenn man auf "Tipp abgeben" drückt, bekommt der User kein Feedback. Im Sinne der Userfreundlichkeit sollte hier in irgendeiner Form eine Erfolgsnachricht angezeigt werden, damit der User mitbekommt: da ist was passiert

**Comment by tobire** [comment]
Außerdem sollten die Tipps nach der Abgabe neu geladen werden, damit mögliche Fehleingaben korrekt dargestellt werden.
